---
label: project
hide_body: true
is_partial: true
fields:
- type: text
  label: Description
  name: description
  config:
    required: true
- type: file
  name: image_left
  label: Image Left
- type: file
  name: image_right
  label: image right
